/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TripRouteImport } from './routes/trip'
import { Route as AddKindRouteImport } from './routes/add.$kind'
import { Route as AddPhotosRouteImport } from './routes/add.photos'
import { Route as CityCityIdRouteImport } from './routes/city.$cityId'
import { Route as EntryEntryIdRouteImport } from './routes/entry.$entryId'
import { Route as TripIndexRouteImport } from './routes/trip.index'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripTripIdExportRouteImport } from './routes/trip.$tripId.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const AddKindRoute = AddKindRouteImport.update({
  id: '/add/$kind',
  path: '/add/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPhotosRoute = AddPhotosRouteImport.update({
  id: '/add/photos',
  path: '/add/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityIdRoute = CityCityIdRouteImport.update({
  id: '/city/$cityId',
  path: '/city/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryEntryIdRoute = EntryEntryIdRouteImport.update({
  id: '/entry/$entryId',
  path: '/entry/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIndexRoute = TripIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TripRoute,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdExportRoute = TripTripIdExportRouteImport.update({
  id: '/$tripId/export',
  path: '/$tripId/export',
  getParentRoute: () => TripRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dining': typeof DiningRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/trip': typeof TripRouteWithChildren
  '/add/$kind': typeof AddKindRoute
  '/add/photos': typeof AddPhotosRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trip/': typeof TripIndexRoute
  '/trip/$tripId/export': typeof TripTripIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dining': typeof DiningRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/add/$kind': typeof AddKindRoute
  '/add/photos': typeof AddPhotosRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trip': typeof TripIndexRoute
  '/trip/$tripId/export': typeof TripTripIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dining': typeof DiningRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/trip': typeof TripRouteWithChildren
  '/add/$kind': typeof AddKindRoute
  '/add/photos': typeof AddPhotosRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trip/': typeof TripIndexRoute
  '/trip/$tripId/export': typeof TripTripIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dining'
    | '/memories'
    | '/settings'
    | '/trip'
    | '/add/$kind'
    | '/add/photos'
    | '/city/$cityId'
    | '/entry/$entryId'
    | '/trips/new'
    | '/trip/'
    | '/trip/$tripId/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dining'
    | '/memories'
    | '/settings'
    | '/add/$kind'
    | '/add/photos'
    | '/city/$cityId'
    | '/entry/$entryId'
    | '/trips/new'
    | '/trip'
    | '/trip/$tripId/export'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dining'
    | '/memories'
    | '/settings'
    | '/trip'
    | '/add/$kind'
    | '/add/photos'
    | '/city/$cityId'
    | '/entry/$entryId'
    | '/trips/new'
    | '/trip/'
    | '/trip/$tripId/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DiningRoute: typeof DiningRoute
  MemoriesRoute: typeof MemoriesRoute
  SettingsRoute: typeof SettingsRoute
  TripRoute: typeof TripRouteWithChildren
  AddKindRoute: typeof AddKindRoute
  AddPhotosRoute: typeof AddPhotosRoute
  CityCityIdRoute: typeof CityCityIdRoute
  EntryEntryIdRoute: typeof EntryEntryIdRoute
  TripsNewRoute: typeof TripsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/$kind': {
      id: '/add/$kind'
      path: '/add/$kind'
      fullPath: '/add/$kind'
      preLoaderRoute: typeof AddKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/photos': {
      id: '/add/photos'
      path: '/add/photos'
      fullPath: '/add/photos'
      preLoaderRoute: typeof AddPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$cityId': {
      id: '/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/city/$cityId'
      preLoaderRoute: typeof CityCityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$entryId': {
      id: '/entry/$entryId'
      path: '/entry/$entryId'
      fullPath: '/entry/$entryId'
      preLoaderRoute: typeof EntryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/': {
      id: '/trip/'
      path: '/'
      fullPath: '/trip/'
      preLoaderRoute: typeof TripIndexRouteImport
      parentRoute: typeof TripRoute
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/export': {
      id: '/trip/$tripId/export'
      path: '/$tripId/export'
      fullPath: '/trip/$tripId/export'
      preLoaderRoute: typeof TripTripIdExportRouteImport
      parentRoute: typeof TripRoute
    }
  }
}

interface TripRouteChildren {
  TripIndexRoute: typeof TripIndexRoute
  TripTripIdExportRoute: typeof TripTripIdExportRoute
}

const TripRouteChildren: TripRouteChildren = {
  TripIndexRoute: TripIndexRoute,
  TripTripIdExportRoute: TripTripIdExportRoute,
}

const TripRouteWithChildren = TripRoute._addFileChildren(TripRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DiningRoute: DiningRoute,
  MemoriesRoute: MemoriesRoute,
  SettingsRoute: SettingsRoute,
  TripRoute: TripRouteWithChildren,
  AddKindRoute: AddKindRoute,
  AddPhotosRoute: AddPhotosRoute,
  CityCityIdRoute: CityCityIdRoute,
  EntryEntryIdRoute: EntryEntryIdRoute,
  TripsNewRoute: TripsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
